---
version: '3'
services:
  sthf-remove-photo-object:
    build: .
    container_name: sthf-remove-photo-object
    restart: unless-stopped
    ports:
    - 41003:8501
    volumes:
    - .:/app
    environment:
    - TZ=Asia/Jakarta
    # command: streamlit run sdc.py